GET http://localhost:3001/api/persons/

###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Kobe Bryant",
    "number": "24"
}

###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "number": "2000-2002"
}

###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Shaquille O'Neal"
}